

import '../models/fish_model.dart';

final List<Fish> app_fish_list = [
  Fish(species: "Chiloscyllium burmensis", commonName: "Burmese bambooshark", bengaliName: "মুইছিয়া হাঙ্গর", IUCN: "LC"),
  Fish(species: "Chiloscyllium griseum", commonName: "Grey bambooshark", bengaliName: "মুইছিয়া হাঙ্গর", IUCN: "NT"),
  Fish(species: "Chiloscyllium hasseltii", commonName: "Hasselt's ", bengaliName: "মুইছিয়া হাঙ্গর", IUCN: "NE"),
  Fish(species: "Chiloscyllium indicum", commonName: "Slender Shark", bengaliName: "মুইছিয়া হাঙ্গর", IUCN: "NT"),
  Fish(species: "Chiloscyllium punctatum", commonName: "Brownbanded bamboo Shark", bengaliName: "বিলাই হাঙ্গর", IUCN: "NT"),
  Fish(species: "Stegostoma fasciatum", commonName: "Zebra Shark", bengaliName: "বাঘা হাঙ্গর", IUCN: "EN"),
  Fish(species: "Rhincodon typus", commonName: "Whale Shark", bengaliName: "তিমি হাঙ্গর", IUCN: "EN"),
  Fish(species: "Alopias vulpinus", commonName: "Thresher", bengaliName: "থ্রেসার", IUCN: "VU"),
  Fish(species: "Atelomycterus marmoratus", commonName: "Coral Catshark", bengaliName: "হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus amblyrhynchos", commonName: "Black creeper shark", bengaliName: "কালো লতা বলি হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus amboinensis", commonName: "Pigeye shark", bengaliName: "বলি হাঙ্গর", IUCN: "DD"),
  Fish(species: "Carcharhinus dussumier", commonName: "Whitecheek Shark", bengaliName: "হাঙ্গর", IUCN: "EN"),
  Fish(species: "Carcharhinus falciformis", commonName: "Silky Shark", bengaliName: "নীল হাঙ্গর", IUCN: "VU"),
  Fish(species: "Carcharhinus leucas", commonName: "Bull Shark", bengaliName: "বলি হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus limbatus", commonName: "Blacktip Shark", bengaliName: "কালা হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus macloti", commonName: "Hardnose Shark", bengaliName: "টুইট্টা হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus melanopterus", commonName: "Blacktip reef shark", bengaliName: "কালা হাঙ্গর", IUCN: "NT"),
  Fish(species: "Carcharhinus sorrah", commonName: "Spot-tail shark", bengaliName: "হাঙ্গর", IUCN: "NT"),
  Fish(species: "Galeocerdo cuvier", commonName: "Tiger shark", bengaliName: "বাঘা হাঙ্গর", IUCN: "NT"),
  Fish(species: "Glyphis gangeticus", commonName: "Ganges shark", bengaliName: "কাঙ্গট", IUCN: "CR"),
  Fish(species: "Glyphis glyphis", commonName: "Speartooth shark", bengaliName: "হাঙ্গর", IUCN: "EN"),
  Fish(species: "Rhizoprionodon acutus", commonName: "Milk Shark", bengaliName: "নাক চোক্ষা হাঙ্গর", IUCN: "LC"),
  Fish(species: "Scoliodon laticaudus", commonName: "Spadenose shark", bengaliName: "ছুরি হাঙ্গর", IUCN: "NT"),
  Fish(species: "Scoliodon macrorhynchos", commonName: "Pacific spadenose shark", bengaliName: "ছুরি হাঙ্গর", IUCN: "NE"),
  Fish(species: "Triaenodon obesus", commonName: "Whitetip reef shark", bengaliName: "হাঙ্গর", IUCN: "NT"),
  Fish(species: "Chaenogaleus macrostoma", commonName: "Hooktooth shark", bengaliName: "বর্শি দেঁতো হাঙ্গর", IUCN: "VU"),
  Fish(species: "Hemipristis elongata", commonName: "Snaggletooth shark", bengaliName: "স্ন্যাগলটুথ হাঙ্গর", IUCN: "VU"),
  Fish(species: "Eusphyra blochii", commonName: "Winghead shark", bengaliName: "বড়ো হাতুড়ি হাঙ্গর", IUCN: "EN"),
  Fish(species: "Sphyrna lewini", commonName: "Scalloped hammerhead", bengaliName: "হাতুড়ি হাঙ্গর", IUCN: "VU"),
  Fish(species: "Sphyrna mokarran", commonName: "Great hammerhead", bengaliName: "হাতুড়ি হাঙ্গর", IUCN: "CR"),
  Fish(species: "Sphyrna tudes", commonName: "Smalleye hammerhead", bengaliName: "ছোট হাতুড়ি হাঙ্গর", IUCN: "VU"),
  Fish(species: "Sphyrna zygaena", commonName: "Smooth hammerhead", bengaliName: "মসৃণ হাতুড়ি হাঙ্গর", IUCN: "VU"),
  Fish(species: " Galeorhinus galeus", commonName: "Tope shark", bengaliName: "টোপ হাঙ্গর", IUCN: "VU"),
  Fish(species: "Mustelus griseus", commonName: "Spotless smooth-hound", bengaliName: "হাঙ্গর", IUCN: "DD"),
  Fish(species: "Mustelus manazo", commonName: "Starspotted smooth-hound", bengaliName: "হাঙ্গর", IUCN: "DD"),
  Fish(species: "Mustelus mosis", commonName: "Arabian smoothhound", bengaliName: "হাঙ্গর", IUCN: "NT"),
  Fish(species: "Narcine brunnea", commonName: "Spotless smooth-hound", bengaliName: "বাদামি বিদ্যুৎ মাছ", IUCN: "VU"),
  Fish(species: "Narcine prodorsalis", commonName: "Tonkin numbfish", bengaliName: "বিদ্যুৎ মাছ", IUCN: "DD"),
  Fish(species: "Narcine timlei", commonName: "Spotted numbfish", bengaliName: "বিদ্যুৎ মাছ", IUCN: "DD"),
  Fish(species: "Narke dipterygia", commonName: "Numbray", bengaliName: "বিদ্যুৎ মাছ", IUCN: "DD"),
  Fish(species: "Rhina ancylostoma", commonName: "Bowmouth ", bengaliName: "তিতামারমারি", IUCN: "CR"),
  Fish(species: "Rhinobatos annandalei", commonName: "Annandale's guitarfish", bengaliName: "মাটিয়া বাইল্যা", IUCN: "DD"),
  Fish(species: "Rhynchobatus djiddensis", commonName: "Giant guitarfish", bengaliName: "তিতামারমারি", IUCN: "CR"),
  Fish(species: "Glaucostegus granulatus", commonName: "Granulated guitarfish", bengaliName: "পিতাম্বরি", IUCN: "CR"),
  Fish(species: "Glaucostegus typus", commonName: "Giant shovelnose ray", bengaliName: "পিতাম্বরি", IUCN: "CR"),
  Fish(species: "Anoxypristis cuspidata", commonName: "Pointed sawfish", bengaliName: "করাতি হাঙ্গর", IUCN: "EN"),
  Fish(species: "Pristis microdon", commonName: "Largetooth sawfish", bengaliName: "করাতি হাঙ্গর", IUCN: "CR"),
  Fish(species: "Pristis pectinata", commonName: "Smalltooth sawfish", bengaliName: "করাতি হাঙ্গর", IUCN: "CR"),
  Fish(species: "Pristis pristis", commonName: "Common ", bengaliName: "করাতি হাঙ্গর", IUCN: "CR"),
  Fish(species: "Pristis zijsron", commonName: "Longcomb sawfish", bengaliName: "করাতি হাঙ্গর", IUCN: "CR"),
  Fish(species: "Brevitrygon imbricata", commonName: "Scaly whipray", bengaliName: "হাউশ পাতা", IUCN: "DD"),
  Fish(species: "Brevitrygon walga", commonName: "Dwarf whipray", bengaliName: "হাউশ পাতা", IUCN: "NE"),
  Fish(species: "Hemitrygon bennettii", commonName: "Bennett’s stingray", bengaliName: "হাউশ পাতা", IUCN: "NE"),
  Fish(species: "Himantura ", commonName: "Ganges stingray", bengaliName: "হাউশ পাতা", IUCN: "NE"),
  Fish(species: "Himantura marginata", commonName: "Blackedge whipray", bengaliName: "হাউশ পাতা", IUCN: "DD"),
  Fish(species: "Himantura uarnak", commonName: "Honeycomb ", bengaliName: "চিত্রা হাউশ", IUCN: "VU"),
  Fish(species: "Himantura undulata", commonName: "Leopard whipray", bengaliName: "চিত্রা হাউশ", IUCN: "VU"),
  Fish(species: "Maculabatis gerrardi", commonName: "Sharpnose stingray", bengaliName: "হাউশ পাতা", IUCN: "VU"),
  Fish(species: "Maculabatis pastinacydes", commonName: "Round whipray", bengaliName: "হাউশ পাতা", IUCN: "VU"),
  Fish(species: "Neotrygon indica", commonName: "Bluespotted stingray", bengaliName: "চিত্রা হাউশ", IUCN: "DD"),
  Fish(species: "Tastinachus gracilicaudus", commonName: "Narrow tail stingray", bengaliName: "হাউশ পাতা", IUCN: "NE"),
  Fish(species: "Pastinachus sephen", commonName: "Cowtail stingray", bengaliName: "হাউশ পাতা", IUCN: "NT"),
  Fish(species: "Pateobatis bleekeri", commonName: "Bleeker’s whipray", bengaliName: "হাউশ পাতা", IUCN: "NE"),
  Fish(species: "Pateobatis uarnacoides", commonName: "Bleeker’s whipray", bengaliName: "হাউশ পাতা", IUCN: "VU"),
  Fish(species: "Taeniura lymma", commonName: "Ribbontail stingray", bengaliName: "শাপলাপাতা", IUCN: "NT"),
  Fish(species: "Taeniurops meyeni", commonName: "Round ribbontail ray", bengaliName: "হাউশ পাতা", IUCN: "VU"),
  Fish(species: "Telatrygon zugei", commonName: "Sharp snout Stingray", bengaliName: "ছোটো মুখো হাউশ", IUCN: "NT"),
  Fish(species: "Urogymnus asperrimus", commonName: "Porcupine ray", bengaliName: "হাউশ পাতা", IUCN: "VU"),
  Fish(species: "Gymnura micrura", commonName: "Smooth butterfly ray", bengaliName: "পদ্মামনি", IUCN: "DD"),
  Fish(species: "Gymnura poecilura", commonName: "Long-tailed butterfly ray", bengaliName: "কুলতা", IUCN: "NT"),
  Fish(species: "Aetobatus narinari", commonName: "Spotted eagle ray", bengaliName: "চিলমাছ", IUCN: "NT"),
  Fish(species: "Aetomylaeus maculatus", commonName: "Mottled eagle ray", bengaliName: "শঙ্খচিল", IUCN: "EN"),
  Fish(species: "Aetomylaeus nichofii", commonName: "Banded eagle ray", bengaliName: "শঙ্খচিল", IUCN: "VU"),
  Fish(species: "Mobula birostris", commonName: "Giant manta", bengaliName: "দৈত্য মান্তা", IUCN: "VU"),
  Fish(species: "Mobula eregoodootenkee", commonName: "Longhorned mobula", bengaliName: "দিও মাছ", IUCN: "NT"),
  Fish(species: "Mobula japanica", commonName: "Spinetail mobula", bengaliName: "দিও মাছ", IUCN: "NT"),
  Fish(species: "Mobula kuhlii", commonName: "Shortfin devil ray", bengaliName: "দিও মাছ", IUCN: "EN"),
  Fish(species: "Mobula mobular", commonName: "Giant devil ray", bengaliName: "দিও মাছ", IUCN: "EN"),
  Fish(species: "Mobula tarapacana", commonName: "Chilean devil ray", bengaliName: "দিও মাছ", IUCN: "EN"),
  Fish(species: "Rhinoptera javanica", commonName: "Flapnose ray", bengaliName: "শঙ্খচিল", IUCN: "VU"),
  Fish(species: "Rhinoptera neglect", commonName: "Australian cownose ray", bengaliName: "শঙ্খচিল", IUCN: "DD"),
  Fish(species: "Elops machnata", commonName: "Tenpounder", bengaliName: "সোলেমানি মাছ", IUCN: "LC"),
  Fish(species: "Megalops cyprinoides", commonName: "Indo-Pacific tarpon", bengaliName: "নানচিল কোরাল", IUCN: "DD"),
  Fish(species: "Echidna nebulosa", commonName: "Starry moray", bengaliName: "তারা বাইম", IUCN: "LC"),
  Fish(species: "Gymnothorax favagineus", commonName: "Laced moray", bengaliName: "চিতা বাঘ মাছ", IUCN: "LC"),
  Fish(species: "Gymnothorax prolatus", commonName: "Moray eel", bengaliName: "সাপ মাছ", IUCN: "DD"),
  Fish(species: "Gymnothorax pseudothyrsoideus", commonName: "Highfin moray", bengaliName: "মেটকা", IUCN: "LC"),
  Fish(species: "Gymnothorax punctatus", commonName: "Red Sea whitespotted moray", bengaliName: "বামশ", IUCN: "LC"),
  Fish(species: "Gymnothorax ", commonName: "Reticulated moray", bengaliName: "চিত্রা ইল", IUCN: "NE"),
  Fish(species: "Gymnothorax tile", commonName: "Indian mud moray", bengaliName: "ইল", IUCN: "LC"),
  Fish(species: "Gymnothorax undulatus", commonName: "Undulated moray", bengaliName: "মাউরি বাইম", IUCN: "LC"),
  Fish(species: "Strophidon sathete", commonName: "Slender Giant ", bengaliName: "সাপ মাছ", IUCN: "NE"),
  Fish(species: "Caecula pterygera", commonName: "Finny snake eel", bengaliName: "হিযরা", IUCN: "NE"),
  Fish(species: "Lamnostoma ", commonName: "Oriental wormeel", bengaliName: "হিযরা", IUCN: "LC"),
  Fish(species: "Muraenichthys gymnopterus", commonName: "Worm-eel", bengaliName: "সাপ মাছ", IUCN: "NE"),
  Fish(species: "Pisodonophis boro", commonName: "Rice-paddy eel", bengaliName: "বামশ", IUCN: "LC"),
  Fish(species: "Pisodonophis cancrivorus", commonName: "Longfin snakeeel", bengaliName: "বড়ো পাখনা সাপ মাছ", IUCN: "NE"),
  Fish(species: "Congresox talabon", commonName: "Yellow pike conger", bengaliName: "কামিলা", IUCN: "NE"),
  Fish(species: "Congresox talabonoides", commonName: "Indian pike conger", bengaliName: "কামিলা", IUCN: "NE"),
  Fish(species: "Muraenesox bagio", commonName: "Common pike conger", bengaliName: "কামিলা", IUCN: "NE"),
  Fish(species: "Muraenesox cinereus", commonName: "Daggertooth pike conger", bengaliName: "কামিলা", IUCN: "NE"),
  Fish(species: "Ariosoma anago", commonName: "Silvery conger", bengaliName: "কামিলা", IUCN: "DD"),
  Fish(species: "Ariosoma gnanadossi", commonName: "Eel", bengaliName: "কামিলা", IUCN: "LC"),
  Fish(species: "Conger cinereus", commonName: "Longfin African conger", bengaliName: "কামিলা", IUCN: "LC"),
  Fish(species: "Conger conger", commonName: "European conger", bengaliName: "কামিলা", IUCN: "LC"),
  Fish(species: "Heteroconger perissodon", commonName: "Black garden eel", bengaliName: "কামিলা", IUCN: "LC"),
  Fish(species: "Uroconger lepturus", commonName: "Slender conger", bengaliName: "কামিলা", IUCN: "LC"),
  Fish(species: "Anguilla bengalensis", commonName: "Indian mottled eel", bengaliName: "বাইম মাছ", IUCN: "LC"),
  Fish(species: "Anguilla bicolor", commonName: "Indonesian shortfin eel", bengaliName: "বাইম মাছ", IUCN: "NT"),
  Fish(species: "Anguilla celebesensis", commonName: "Celebes longfin eel", bengaliName: "সেলেবস লংফিন ইল", IUCN: "NT"),
  Fish(species: "Anguilla marmorata", commonName: "Giant mottled eel", bengaliName: "বাউ বাইম", IUCN: "DD"),
  Fish(species: "Ilisha elongata", commonName: "Elongate ilisha", bengaliName: "রামগাসা", IUCN: "LC"),
  Fish(species: "Ilisha filigera", commonName: "Coromandel ", bengaliName: "বড়ো চউক্ষা", IUCN: "DD"),
  Fish(species: "Ilisha megaloptera", commonName: "Bigeye ilisha", bengaliName: "চউক্ষা", IUCN: "LC"),
  Fish(species: "Ilisha melastoma", commonName: "Indian ilisha", bengaliName: "চউক্ষা", IUCN: "LC"),
  Fish(species: "Opisthopterus tardoore", commonName: "Tardoore", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Pellona ditchela", commonName: "Indian pellona", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Raconda russeliana", commonName: "Raconda", bengaliName: "কুইন্যা ফাইস্যা", IUCN: "LC"),
  Fish(species: "Coilia dussumieri", commonName: "Goldspotted grenadier anchovy", bengaliName: "ওলুয়া", IUCN: "LC"),
  Fish(species: "Coilia mystus", commonName: "Osbeck's grenadier anchovy", bengaliName: "ওলুয়া", IUCN: "EN"),
  Fish(species: "Coilia neglecta", commonName: "Neglected ", bengaliName: "ওলুয়া", IUCN: "LC"),
  Fish(species: "Coilia ramcarati", commonName: "Ramcarat grenadier anchovy", bengaliName: "বগা ওলুয়া", IUCN: "DD"),
  Fish(species: "Coilia reynaldi", commonName: "Reynald's g. ", bengaliName: "ওলুয়া", IUCN: "LC"),
  Fish(species: "Coilia macrognathos", commonName: "Longjaw g. anchovy", bengaliName: "ওলুয়া", IUCN: "DD"),
  Fish(species: "Setipinna breviceps", commonName: "Shorthead hairfin", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Setipinna taty", commonName: "Scaly hairfin anchovy", bengaliName: "রাম ফাইস্যা", IUCN: "LC"),
  Fish(species: "Setipinna tenuifilis", commonName: "Common ", bengaliName: "ফাইস্যা", IUCN: "DD"),
  Fish(species: "Stolephorus commersonnii", commonName: "Commerson's anchovy", bengaliName: "মলা", IUCN: "LC"),
  Fish(species: "Stolephorus indicus", commonName: "Indian anchovy", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Stolephorus tri", commonName: "Spined anchovy", bengaliName: "কাটা ফাইস্যা", IUCN: "LC"),
  Fish(species: "Thryssa dussumieri", commonName: "Dussumier's thryssa", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Thryssa hamiltonii", commonName: "Hamilton's thryssa", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Thryssa kammalensis", commonName: "Kammal thryssa", bengaliName: "ফাইস্যা", IUCN: "DD"),
  Fish(species: "Thryssa malabarica", commonName: "Malabar thryssa", bengaliName: "ফাইস্যা", IUCN: "DD"),
  Fish(species: "Thryssa mystax", commonName: "Moustached thryssa", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Thryssa purava", commonName: "Oblique Jaw ", bengaliName: "ফাইস্যা", IUCN: "DD"),
  Fish(species: "Thryssa setirostris", commonName: "Longjaw thryssa", bengaliName: "ফাইস্যা", IUCN: "LC"),
  Fish(species: "Chirocentrus dorab", commonName: "Dorab wolfherring", bengaliName: "করাতি চেলা", IUCN: "LC"),
  Fish(species: "Chirocentrus nudus", commonName: "Whitefin wolfherring", bengaliName: "করাতি চেলা", IUCN: "LC"),
  Fish(species: "Anodontostoma chacunda", commonName: "Chacunda gizzard shad", bengaliName: "কই পুটি", IUCN: "LC"),
  Fish(species: "Escualosa ", commonName: "White Sardine", bengaliName: "হিচিড়ি মাছ", IUCN: "LC"),
  Fish(species: "Hilsa kelee", commonName: "Kelee shad", bengaliName: "গুরতা ইলিশ", IUCN: "LC"),
  Fish(species: "Nematalosa nasus", commonName: "Bloch's gizzard shad", bengaliName: "খইরা", IUCN: "LC"),
  Fish(species: "Sardinella albella", commonName: "White sardinella", bengaliName: "চাপিলা", IUCN: "LC"),
  Fish(species: "Sardinella fimbriata", commonName: "Fringescale sardinella", bengaliName: "খাইরা", IUCN: "LC"),
  Fish(species: "Sardinella gibbosa", commonName: "Gold stripe sardine", bengaliName: "সোনালি খাইরা", IUCN: "LC"),
  Fish(species: "Sardinella longiceps", commonName: "Imdian Oil Sardine", bengaliName: "খইরা", IUCN: "LC"),
  Fish(species: "Sardinella melanura", commonName: "Blacktip sardinella", bengaliName: "চন্দনা", IUCN: "LC"),
  Fish(species: "Tenualosa ilisha", commonName: "Hilsa shad", bengaliName: "ইলিশ", IUCN: "LC"),
  Fish(species: "Tenualosa toli", commonName: "Toli shad", bengaliName: "চন্দনা ইলিশ", IUCN: "LC"),
  Fish(species: "Dussumieria acuta", commonName: "Rainbow sardine", bengaliName: "নলিয়া", IUCN: "LC"),
  Fish(species: "Dussumieria elopsoides", commonName: "Slender rainbow sardine", bengaliName: "মরিচা", IUCN: "LC"),
  Fish(species: "Chanos chanos", commonName: "Milkfish", bengaliName: "দুইধ্যা মাছ", IUCN: "LC"),
  Fish(species: "Plotosus canius", commonName: "Gray ell catfish", bengaliName: "কাইন মাগুর", IUCN: "NE"),
  Fish(species: "Plotosus lineatus", commonName: "Striped ell tail catfish", bengaliName: "সাগর কাইন", IUCN: "NE"),
  Fish(species: "Arius    arius", commonName: "Threadfin sea catfish", bengaliName: "কাটা মাছ", IUCN: "LC"),
  Fish(species: "Arius gagore", commonName: "Gagora Catfish", bengaliName: "কাটা মাছ", IUCN: "NT"),
  Fish(species: "Arius     jella", commonName: "Gagora catfish", bengaliName: "কাটা মাছ", IUCN: "NE"),
  Fish(species: "Arius maculatus", commonName: "Spotted  catfish", bengaliName: "কাটা মাছ", IUCN: "NE"),
  Fish(species: "Arius venosus", commonName: "Yellow Sea Catfish", bengaliName: "কাটা ভেনি", IUCN: "NE"),
  Fish(species: "Batrachocephalus mino", commonName: "Beardless sea catfish", bengaliName: "কাটাবুখা", IUCN: "NE"),
  Fish(species: "Cephalocassis jatia", commonName: "River catfish", bengaliName: "কাটা মাছ", IUCN: "DD"),
  Fish(species: "Hexanematichthys sagor", commonName: "Sagor catfish", bengaliName: "সাগর গুইজ্জ্যা", IUCN: "NE"),
  Fish(species: "Ketengus typus", commonName: "Bigmouth sea catfish", bengaliName: "মেধা", IUCN: "NE"),
  Fish(species: "Nemapteryx caelata", commonName: "Engraved cat fish", bengaliName: "কাটা মাছ", IUCN: "NE"),
  // Fish(species: "Nemapteryx macronotacantha", commonName: "", bengaliName: "কাটানিল", IUCN: "NE"),
  Fish(species: "Nemapteryx nenga", commonName: "Engraved Catfish", bengaliName: "কাটা গোগাত", IUCN: "NE"),
  Fish(species: "Netuma bilineata", commonName: "Bronze catfish", bengaliName: "কাটা মাছ", IUCN: "NE"),
  Fish(species: "Netuma thalassina", commonName: "Giant catfish", bengaliName: "কাটা মাছ", IUCN: "NE"),
  Fish(species: "Osteogeneiosus militaris", commonName: "Soldier catfish", bengaliName: "আপুইয়া", IUCN: "NE"),
  Fish(species: "Plicofollis dussumieri", commonName: "Blacktip sea catfish", bengaliName: "কাটা", IUCN: "LC"),
  Fish(species: "Plicofollis layardi", commonName: "Thinspine sea catfish", bengaliName: "কাটা", IUCN: "NE"),
  Fish(species: "Plicofollis nella", commonName: "Smoothheaded catfish", bengaliName: "কাটা নিলা", IUCN: "NE"),
  Fish(species: "Plicofollis platystomus", commonName: "Flatmouth sea catfish", bengaliName: "সামুদ্রিক কাটা", IUCN: "LC"),
  Fish(species: "Plicofollis tonggol", commonName: "Roughback sea catfish", bengaliName: "সামুদ্রিক কাটা", IUCN: "NE"),
  Fish(species: "Sciades sona", commonName: "Dusky Catfish", bengaliName: "চাই কাটা", IUCN: "NE"),
  Fish(species: "Chlorophthalmus agassizi", commonName: "Shortnose greeneye", bengaliName: "সবুজ চোখি", IUCN: "LC"),
  Fish(species: "Chlorophthalmus corniger", commonName: "Spinyjaw greeneye", bengaliName: "সবুজ চোখি", IUCN: "LC"),
  Fish(species: "Harpadon nehereus", commonName: "Bombay-duck", bengaliName: "লইট্যা", IUCN: "NT"),
  Fish(species: "Saurida gracilis", commonName: "Gracile lizardfish", bengaliName: "টিকটিকি মাছ", IUCN: "LC"),
  Fish(species: "Saurida longimanus", commonName: "Longfin lizardfish", bengaliName: "আঞ্চিলা", IUCN: "LC"),
  Fish(species: "Saurida micropectoralis", commonName: "Shortfin lizardfish", bengaliName: "আঞ্চিলা", IUCN: "LC"),
  Fish(species: "Saurida tumbil", commonName: "Greater lizardfish", bengaliName: "টিকটিকি মাছ", IUCN: "LC"),
  Fish(species: "Saurida undosquamis", commonName: "Brushtooth lizardfish", bengaliName: "টিকটিকি মাছ", IUCN: "LC"),
  Fish(species: "Synodus indicus", commonName: "Indian lizardfish", bengaliName: "আঞ্চিলা", IUCN: "LC"),
  Fish(species: "Trachinocephalus myops", commonName: "Snakefish", bengaliName: "আঞ্চিলা", IUCN: "LC"),
  Fish(species: "Polymixia berndti", commonName: "Pacific beardfish", bengaliName: "", IUCN: "LC"),
  Fish(species: " Zenion leptolepis", commonName: "Elongate dory", bengaliName: "", IUCN: "NE"),
  Fish(species: "Bregmaceros mcclellandi", commonName: "Unicorn Cod", bengaliName: "পুঁইয়া", IUCN: "NE"),
  Fish(species: "Coelorinchus parallelus", commonName: "Spiny grenadier", bengaliName: "ইঁদুর লেইজ্যা", IUCN: "NE"),
  Fish(species: "Coryphaenoides woodmasoni", commonName: "Wood-Mason's ", bengaliName: "ইঁদুর লেইজ্যা", IUCN: "NE"),
  Fish(species: "Hymenocephalus ", commonName: "Glasshead grenadier", bengaliName: "", IUCN: "LC"),
  Fish(species: "Myripristis botche", commonName: "Blacktip soldierfish", bengaliName: "সৈনিক মাছ", IUCN: "LC"),
  Fish(species: "Myripristis hexagona", commonName: "Doubletooth soldierfish", bengaliName: "সৈনিক মাছ", IUCN: "LC"),
  Fish(species: "Myripristis murdjan", commonName: "Pinecone soldierfish", bengaliName: "সৈনিক মাছ", IUCN: "LC"),
  Fish(species: "Myripristis vittata", commonName: "Whitetip soldierfish", bengaliName: "সৈনিক মাছ", IUCN: "LC"),
  Fish(species: "Sargocentron caudimaculatum", commonName: "Silverspot squirrelfish", bengaliName: "রূপাইল কাঠবিড়ালি", IUCN: "LC"),
  Fish(species: "Sargocentron rubrum", commonName: "Redcoat", bengaliName: "সৈনিক মাছ", IUCN: "LC"),
  Fish(species: "Gephyroberyx darwinii", commonName: "Darwin's slimehead", bengaliName: "লাল পাখনা চান্দা", IUCN: "LC"),
  Fish(species: "Brotula multibarbata", commonName: "Goatsbeard brotula", bengaliName: "সমুদ্র মাগুর", IUCN: "LC"),
  Fish(species: "Hypopleuron caninum", commonName: "Whiptail cusk", bengaliName: "সমুদ্র চেউয়া", IUCN: "LC"),
  Fish(species: "Allenbatrachus grunniens", commonName: "Grunting Toadfish", bengaliName: "ব্যাঙ মাছ", IUCN: "NE"),
  Fish(species: "Batrachomoeus", commonName: "Three-spined frogfish", bengaliName: "তিন কাটা ব্যাঙ মাছ", IUCN: "NE"),
  Fish(species: "Colletteichthys dussumieri", commonName: "Flat toadfish", bengaliName: "ব্যাঙ মাছ", IUCN: "NE"),
  Fish(species: "Chelon parsia", commonName: "Goldspot Mullet", bengaliName: "বাটা/পারশে", IUCN: "NE"),
  Fish(species: "Ellochelon vaigiensis", commonName: "Square tail mullet", bengaliName: "বাটা", IUCN: "LC"),
  Fish(species: "Liza parsia", commonName: "Goldspot Mullet", bengaliName: "বাটা/পারশে", IUCN: "NE"),
  Fish(species: "Mugil cephalus", commonName: "Flathead grey mullet", bengaliName: "খুরুল বাটা", IUCN: "LC"),
  Fish(species: "Osteomugil cunnesius", commonName: "Long arm mullet", bengaliName: "বাটা", IUCN: "NE"),
  Fish(species: "Paramugil parmatus", commonName: "Broad-mouthed mullet", bengaliName: "বাটা মাছ", IUCN: "NE"),
  Fish(species: "Planiliza planiceps", commonName: "Tade gray mullet", bengaliName: "বাটা মাছ", IUCN: "NE"),
  Fish(species: "Planiliza subviridis", commonName: "Greenback mullet", bengaliName: "বাটা", IUCN: "NE"),
  Fish(species: "Valamugil speigleri", commonName: "Speigler's mullet", bengaliName: "পাতা বাটা", IUCN: "NE"),
  Fish(species: "Cheilopogon furcatus", commonName: "Spotfin flyingfish", bengaliName: "উড়ুমাছ", IUCN: "LC"),
  Fish(species: "Cypselurus comatus", commonName: "Clearwing flyingfish", bengaliName: "উড়ুমাছ", IUCN: "LC"),
  Fish(species: "Cypselurus ", commonName: "Yellowing ", bengaliName: "উড়ুমাছ", IUCN: "NE"),
  Fish(species: "Exocoetus volitans", commonName: "Tropical twowing flyingfish", bengaliName: "উড়ুমাছ", IUCN: "LC"),
  Fish(species: "Hemiramphus far", commonName: "Black-barred halfbeak", bengaliName: "এক ঠোঁটে", IUCN: "NE"),
  Fish(species: "Hemiramphus marginatus", commonName: "Yellowtip halfbeak", bengaliName: "এক ঠোঁটে", IUCN: "Lc"),
  Fish(species: "Hyporhamphus limbatus", commonName: "Congaturi halfbeak", bengaliName: "এক ঠোঁইট্যা", IUCN: "LC"),
  Fish(species: "Hyporhamphus quoyi", commonName: "Quoy's garfish", bengaliName: "এক ঠোঁইট্যা", IUCN: "NE"),
  Fish(species: "Hyporhamphus unifasciatus", commonName: "Common ", bengaliName: "এক ঠোঁটে", IUCN: "LC"),
  Fish(species: "Rhynchorhamphus georgii", commonName: "Long billed half beak", bengaliName: "এক ঠোঁটে", IUCN: "NE"),
  Fish(species: "Zenarchopterus buffonis", commonName: "Buffon's rivergarfish", bengaliName: "এক ঠোঁটে", IUCN: "NE"),
  Fish(species: "Zenarchopterus dispar", commonName: "Feathered rivergarfish", bengaliName: "এক ঠোঁটে", IUCN: "LC"),
  Fish(species: "Ablennes hians", commonName: "Flat needlefish", bengaliName: "এক ঠোঁটে", IUCN: "LC"),
  Fish(species: "Strongylura leiura", commonName: "Banded needlefish", bengaliName: "কাকিলা", IUCN: "NE"),
  Fish(species: "Strongylura strongylura", commonName: "Spottail needlefish", bengaliName: "কাইক্কা", IUCN: "NE"),
  Fish(species: "Tylosurus crocodilus", commonName: "Hound needlefish", bengaliName: "কাইক্কা", IUCN: "LC"),
  Fish(species: "Psettodes belcheri", commonName: "Halibut", bengaliName: "বড়ো ঠুইট্টা", IUCN: "DD"),
  Fish(species: "Psettodes bennettii", commonName: "Spiny turbot", bengaliName: "সমুদ্র সরবতি", IUCN: "DD"),
  Fish(species: "Psettodes erumei", commonName: "Indian halibut", bengaliName: "সমুদ্র সরবতি", IUCN: "NE"),
  Fish(species: "Brachypleura novaezeelandiae", commonName: "Yellow-dabbled flounder", bengaliName: "সমুদ্র সরবতি", IUCN: "LC"),
  Fish(species: "Cephalopsetta ventrocellatus", commonName: "Large-tooth flounder", bengaliName: "সমুদ্র সরবতি", IUCN: "DD"),
  Fish(species: "Pseudorhombus arsius", commonName: "Largetooth flounder", bengaliName: "বাঁশপাতা", IUCN: "NE"),
  Fish(species: "Pseudorhombus elevatus", commonName: "Deep flounder", bengaliName: "চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Pseudorhombus javanicus", commonName: "Javan flounder", bengaliName: "বড়ো দাতি চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Pseudorhombus malayanus", commonName: "Malayan flounder", bengaliName: "চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Pseudorhombus triocellatus", commonName: "Three spotted flounders", bengaliName: "তিনফোটা চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Paralichthodes algoensis", commonName: "Peppered flounder", bengaliName: "চ্যাপ্টা মাছ", IUCN: "LC"),
  Fish(species: "Arnoglossus aspilos", commonName: "Spotless lefteye flounder", bengaliName: "চ্যাপ্টা মাছ", IUCN: "LC"),
  Fish(species: "Bothus myriaster", commonName: "Indo-Pacific oval flounder", bengaliName: "চ্যাপ্টা মাছ", IUCN: "LC"),
  Fish(species: "Grammatobothus polyophthalmus", commonName: "Threespot flounder", bengaliName: "তিনফোটা চ্যাপ্টা মাছ", IUCN: "LC"),
  Fish(species: "Laeops nigrescens", commonName: "Lefteye flounders", bengaliName: "বামচউখা চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Aesopia cornuta", commonName: "Unicorn sole", bengaliName: "শিঙরা জেবরা", IUCN: "LC"),
  Fish(species: "Brachirus orientalis", commonName: "Oriental sole", bengaliName: "বটপাতা/কাঠালপাতা", IUCN: "NE"),
  Fish(species: "Brachirus pan", commonName: "Sole", bengaliName: "পাতা মাছ", IUCN: "LC"),
  Fish(species: "Synaptura commersonnii", commonName: "Commerson's sole", bengaliName: "সরবতি", IUCN: "DD"),
  Fish(species: "Heteromycteris oculus", commonName: "Eyed sole", bengaliName: "", IUCN: "NE"),
  Fish(species: "Solea elongata", commonName: "Elongate sole", bengaliName: "", IUCN: "NE"),
  Fish(species: "Solea ovata", commonName: "Ovate sole", bengaliName: "পাতা মাছ", IUCN: "NE"),
  Fish(species: "Zebrias altipinnis", commonName: "Zebra sole", bengaliName: "ডোরা সোল", IUCN: "LC"),
  Fish(species: "Zebrias quagga", commonName: "Fingerfin zebra sole", bengaliName: "জেব্রা সোল", IUCN: "NE"),
  Fish(species: "Zebrias synapturoides", commonName: "Indian  zebra sole", bengaliName: "জেব্রা সরবতি", IUCN: "NE"),
  Fish(species: "Zebrias zebra", commonName: "Zebra sole", bengaliName: "জেব্রা সরবতি", IUCN: "NE"),
  Fish(species: "Cynoglossus arel", commonName: "Largescale tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus bilineatus", commonName: "Fourlined tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus capensis", commonName: "Sand tonguefish", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus cynoglossus", commonName: "Bengal tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "LC"),
  Fish(species: "Cynoglossus kopsii", commonName: "Long tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus lida", commonName: "Roughscaled tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus lingua", commonName: "Long tonguesole", bengaliName: "লম্বু কুকুর জিহবা", IUCN: "LC"),
  Fish(species: "Cynoglossus macrolepidotus", commonName: "Largescaled tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Cynoglossus macrostomus", commonName: "Malabar tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "VU"),
  Fish(species: "Cynoglossus puncticeps", commonName: "Speckled tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Paraplagusia bilineata", commonName: "Doublelined tonguesole", bengaliName: "জিহবা সোল", IUCN: "NE"),
  Fish(species: "Symphurus", commonName: "Sevenband tonguesole", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Symphurus", commonName: "Sand tonguefish", bengaliName: "কুকুর জিহবা", IUCN: "NE"),
  Fish(species: "Centriscus scutatus", commonName: "grooved razor fish", bengaliName: "চিরুনি মাছ", IUCN: "LC"),
  Fish(species: "Fistularia commersoni", commonName: "Bluespotted cornetfish", bengaliName: "বংশি বাঁশি", IUCN: "LC"),
  Fish(species: "Fistularia petimba", commonName: "Red cornetfish", bengaliName: "বংশি বাঁশি", IUCN: "NE"),
  Fish(species: "Hippocampus kuda", commonName: "Spotted seashore", bengaliName: "সীসোর", IUCN: "VU"),
  Fish(species: "Ichthyocampus carce", commonName: "Pipefish", bengaliName: "পাইপ মাছ", IUCN: "LC"),
  Fish(species: "Trachyrhamphus serratus", commonName: "Crested pipefish", bengaliName: "সরু লেজা ঠুটে", IUCN: "DD"),
  Fish(species: "Eleutheronema tetradactylum", commonName: "Fourfinger Threadfin", bengaliName: "তাইলা", IUCN: "NE"),
  Fish(species: "Filimanus heptadactyla", commonName: "Sevenfinger threadfin", bengaliName: "তাইলা", IUCN: "LC"),
  Fish(species: "Polydactylus mullani", commonName: "Arabian blackspot threadfin", bengaliName: "লাখুয়া", IUCN: "NE"),
  Fish(species: "Polydactylus plebeius", commonName: "Striped threadfin", bengaliName: "ছোটো লাখুয়া", IUCN: "NE"),
  Fish(species: "Polydactylus sexfilis", commonName: "Six finger threadfin", bengaliName: "সোনা তাইলা", IUCN: "NE"),
  Fish(species: "Polydactylus sextarius", commonName: "Blackspot threadfin", bengaliName: "কালা তাইলা", IUCN: "NE"),
  Fish(species: "Cynoglossus bilineatus", commonName: "Red cornetfish", bengaliName: "বংশি বাঁশি", IUCN: "LC"),
  Fish(species: "Polynemus paradiseus", commonName: "Paradise threadfin", bengaliName: "তপশে মাছ", IUCN: "NE"),
  Fish(species: "Kurtus indicus", commonName: "Indian hump head", bengaliName: "ছোটো ফাইস্যা", IUCN: "NE"),
  Fish(species: "Apogonichthyoides maculipinnis", commonName: "Specklehead cardinalfish", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Apogonichthyoides sialis", commonName: "Twinbar ", bengaliName: "দুইদাগি", IUCN: "NE"),
  Fish(species: "Fibramia thermalis", commonName: "Half-barred cardinal", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Jaydia ellioti", commonName: "Flag-in cardinalfish", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Jaydia queketti", commonName: "Spotfin cardinal", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Lepidamia kalosoma", commonName: "Pinstripe cardinalfish", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus cookii", commonName: "Pinstripe cardinalfish", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus endekataenia", commonName: "Candystripe cardinalfish", bengaliName: "পাচ দাগি দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus fasciatus", commonName: "Broadbanded cardinalfish", bengaliName: "মোটাদাগি দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus gularis", commonName: "Gular cardinalfish", bengaliName: "দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus novemfasciatus", commonName: "Sevenstriped cardinalfish", bengaliName: "চারদাগি দুইদ্দ্যা", IUCN: "NE"),
  Fish(species: "Ostorhinchus septemstriatus", commonName: "Sevenband cardinalfish", bengaliName: "তিনদাগি দুইদ্দ্যা", IUCN: "LC"),
  Fish(species: "Acentrogobius cyanomos", commonName: "Blue-spotted ", bengaliName: "নীল ফোঁটা বাইলা", IUCN: "LC"),
  Fish(species: "Acentrogobius viridipunctatus", commonName: "Spotted green goby", bengaliName: "সবুজ বাইলা", IUCN: "LC"),
  Fish(species: "Amblyeleotris steinitzi", commonName: "Steinitz' prawngoby", bengaliName: "চিংড়ি বাইলা", IUCN: "LC"),
  Fish(species: "Apocryptes bato", commonName: "Mudskipper", bengaliName: "চিরিং", IUCN: "LC"),
  Fish(species: "Awaous guamensis", commonName: "Scribbled Goby", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Boleophthalmus boddarti", commonName: "Boddart's goggle-eyed", bengaliName: "চিরিং", IUCN: "LC"),
  Fish(species: "Boleophthalmus dussumieri", commonName: "Mudskipper", bengaliName: "চিরিং/ডাহুক", IUCN: "LC"),
  Fish(species: "Cryptocentrus cinctus", commonName: "Yellow prawngoby", bengaliName: "চিংড়ি বাইলা", IUCN: "NE"),
  Fish(species: "Glossogobius giuris", commonName: "Tank goby", bengaliName: "বাইল্লা", IUCN: "LC"),
  Fish(species: "Gobiopsis macrostoma", commonName: "Longjaw goby", bengaliName: "বাইলা/বেলে", IUCN: "NE"),
  Fish(species: "Odontamblyopus rubicundus", commonName: "Rubicusdus eelgoby", bengaliName: "সাপ বাইলা", IUCN: "LC"),
  Fish(species: "Oxyurichthys papuensis", commonName: "Frogface goby", bengaliName: "ব্যাঙ্মুখো", IUCN: "LC"),
  Fish(species: "Oxyurichthys petersii", commonName: "Peters's goby", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Periophthalmodon schlosseri", commonName: "Giant mudskipper", bengaliName: "বড় চিরিং/ডাহুক", IUCN: "LC"),
  Fish(species: "Periophthalmus barbarus", commonName: "Atlantic mudskipper", bengaliName: "চিরিং", IUCN: "LC"),
  Fish(species: "Pseudapocryptes elongatus", commonName: "Mud Skipper", bengaliName: "চেউয়া", IUCN: "LC"),
  Fish(species: "Scartelaos histophorus", commonName: "Walking goby", bengaliName: "চেউয়া", IUCN: "LC"),
  Fish(species: "Taenioides anguillaris", commonName: "Eel worm goby", bengaliName: "চেউয়া", IUCN: "LC"),
  Fish(species: "Taenioides buchanani", commonName: "Burmese gobyeel", bengaliName: "চেউয়া", IUCN: "DD"),
  Fish(species: "Taenioides cirratus (Blyth, 1860)", commonName: "Bearded worm goby", bengaliName: "চেউয়া", IUCN: "DD"),
  Fish(species: "Taenioides esquivel Smith, 1947", commonName: "Bulldog eelgoby", bengaliName: "চেউয়া", IUCN: "NE"),
  Fish(species: "Trypauchen vagina", commonName: "Sada chewa", bengaliName: "সাদা চেউয়া", IUCN: "LC"),
  Fish(species: "Zappa confluentus", commonName: "Slender mudskipper", bengaliName: "কালো চেউয়া", IUCN: "LC"),
  Fish(species: "Ambassis ambassis", commonName: "Commersons glassy", bengaliName: "কাটা চান্দা", IUCN: "LC"),
  Fish(species: "Ambassis nalua", commonName: "Scalloped perchlet", bengaliName: "কাটা চান্দা", IUCN: "LC"),
  Fish(species: "Blenniella periophthalmus", commonName: "Blue-dashed rockskipper", bengaliName: "দাই বাইলা", IUCN: "LC"),
  Fish(species: "Cirripectes castaneus", commonName: "Chestnut eyelash blenny", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Ecsenius bicolor", commonName: "Bicolor blenny", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Istiblennius dussumieri", commonName: "Streaky rockskipper", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Omobranchus punctatus", commonName: "Muzzled blenny", bengaliName: "গাট বাইলা", IUCN: "LC"),
  Fish(species: "Petroscirtes breviceps", commonName: "Stripped poison ", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Salariau fasciatus", commonName: "Jewelled blenny", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Xiphasia setifer", commonName: "Hairtail blenny", bengaliName: "সাপ বাইলা", IUCN: "LC"),
  Fish(species: "Coryphaena equiseligr", commonName: "Pompano ", bengaliName: "ডলফিন মাছ", IUCN: "LC"),
  Fish(species: "Coryphaena hippurus", commonName: "Common", bengaliName: "ডলফিন মাছ", IUCN: "LC"),
  Fish(species: "Rachycentron canadum", commonName: "Cobia", bengaliName: "রাজা গজারি", IUCN: "LC"),
  Fish(species: "Echeneis naucrates", commonName: "Live sharksucker", bengaliName: "হাঙ্গর চাট", IUCN: "LC"),
  Fish(species: "Remora", commonName: "Shark sucker", bengaliName: "হাঙ্গর", IUCN: "LC"),
  Fish(species: "Butis butis", commonName: "Duckbill sleeper", bengaliName: "বাইলা/বেলে", IUCN: "NE"),
  Fish(species: "Butis humeralis", commonName: "Black spot", bengaliName: "বাইলা/বেলে", IUCN: "NE"),
  Fish(species: "Butis melanostigma", commonName: "Sleeper govy", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Eleotris fusca", commonName: "Dusky sleeper", bengaliName: "বাইলা/বেলে", IUCN: "NE"),
  Fish(species: "Eleotris lutea", commonName: "Lutea sleeper", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Alectis ciliaris", commonName: "African ", bengaliName: "পেখম ময়ূরী", IUCN: "LC"),
  Fish(species: "Alectis indica", commonName: "Indian threadfish", bengaliName: "পেখম ময়ূরী", IUCN: "LC"),
  Fish(species: "Alepes djedaba", commonName: "Shrimp scad", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Alepes kleinii", commonName: "Razorbelly scad", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Alepes melanoptera", commonName: "Blackfin scad", bengaliName: "ডোরা ময়ূরী", IUCN: "LC"),
  Fish(species: "Alepes vari", commonName: "Herring scad", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Atropus atropus", commonName: "Cleftbelly trevally", bengaliName: "বাঙ্গাদা", IUCN: "LC"),
  Fish(species: "Atule mate", commonName: "Yellowtail scad", bengaliName: "বোম মাইট্টা", IUCN: "LC"),
  Fish(species: "Carangoides armatus", commonName: "Longfin trevally", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Carangoides chrysophrys", commonName: "Longnose trevally", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Carangoides coeruleopinnatus", commonName: "Coastal trevally", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Carangoides ferdau", commonName: "Blue trevally", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Carangoides hedlandensis", commonName: "Bumpnose ", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Carangoides malabaricus", commonName: "Malabar trevally", bengaliName: "মালাবার মূরি", IUCN: "LC"),
  Fish(species: "Caranx heberi", commonName: "Blacktip trevally", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Caranx hippos", commonName: "Crevalle jack", bengaliName: "", IUCN: "LC"),
  Fish(species: "Caranx ignobilis", commonName: "Giant trevally", bengaliName: "নীলাম্বরি", IUCN: "LC"),
  Fish(species: "Caranx melampygus", commonName: "Bluefin trevally", bengaliName: "নীলাম্বরি", IUCN: "LC"),
  Fish(species: "Caranx sexfasciatus", commonName: "Bigeye trevally", bengaliName: "বড়ো চউক্ষা", IUCN: "LC"),
  Fish(species: "Decapterus kurroides", commonName: "Redtail scad", bengaliName: "লালাম্বুরি", IUCN: "LC"),
  Fish(species: "Decapterus macrosoma", commonName: "Shortfin scad", bengaliName: "লালাম্বুরি", IUCN: "LC"),
  Fish(species: "Decapterus maruadsi", commonName: "Japanese scad", bengaliName: "নীলাম্বরি", IUCN: "LC"),
  Fish(species: "Decapterus russelli", commonName: "Indian scad", bengaliName: "সাদা মাইট্টা", IUCN: "LC"),
  Fish(species: "Elagatis bipinnulata", commonName: "Rainbow runner", bengaliName: "টুটা মাছ", IUCN: "LC"),
  Fish(species: "Gnathanodon speciosus", commonName: "Golden trevally", bengaliName: "ঘোড়া মাইট্টা", IUCN: "LC"),
  Fish(species: "Megalaspis cordyla", commonName: "Torpedo scad", bengaliName: "কাওয়া", IUCN: "LC"),
  Fish(species: "Naucrates ductor", commonName: "Pilotfish", bengaliName: "পাইলট মাছ", IUCN: "LC"),
  Fish(species: "Parastromateus niger", commonName: "Black pomfret", bengaliName: "কালাচান্দা", IUCN: "LC"),
  Fish(species: "Scomberoides commersonnianus", commonName: "Double Spotted Queenfish", bengaliName: "চাপা কড়ি", IUCN: "LC"),
  Fish(species: "Scomberoides lysan", commonName: "Doublespotted queenfish", bengaliName: "চাপা", IUCN: "LC"),
  Fish(species: "Scomberoides tala", commonName: "Barred queenfish", bengaliName: "বোম মাইট্টা", IUCN: "LC"),
  Fish(species: "Scomberoides tol", commonName: "Needlescaled queenfish", bengaliName: "বোম মাইট্টা", IUCN: "LC"),
  Fish(species: "Selar boops", commonName: "Oxeye scad", bengaliName: "শীতাপ", IUCN: "LC"),
  Fish(species: "Selar ", commonName: "Bigeye scad", bengaliName: "বড়ো চউক্ষা", IUCN: "LC"),
  Fish(species: "Selaroides leptolepis", commonName: "Yellowstripe scad", bengaliName: "হলদে ডোরা চউক্ষা", IUCN: "LC"),
  Fish(species: "Seriola rivoliana", commonName: "Longfin yellowtail", bengaliName: "ময়ূরী", IUCN: "LC"),
  Fish(species: "Seriolina nigrofasciata", commonName: "Blackbanded trevally", bengaliName: "কালো ডোরা", IUCN: "LC"),
  Fish(species: "Trachinotus baillonii", commonName: "Small spotted dart", bengaliName: "অঞ্জপুলি", IUCN: "LC"),
  Fish(species: "Trachinotus blochii", commonName: "Snubnose pompano", bengaliName: "কাটা টিক্কা", IUCN: ""),
  Fish(species: "Trachurus indicus", commonName: "Arabian scad", bengaliName: "", IUCN: "VU"),
  Fish(species: "ulua mentalis", commonName: "Longrakered trevally", bengaliName: "চান্দা", IUCN: "LC"),
  Fish(species: "Uraspis uraspis", commonName: "Whitemouth jack", bengaliName: "চান্দা", IUCN: "LC"),
  Fish(species: "Mene maculata", commonName: "Moonfish", bengaliName: "চান চান্দা", IUCN: "NE"),
  Fish(species: "Sphyraena barracuda", commonName: "Great barracuda", bengaliName: "ধারকুটা", IUCN: "LC"),
  Fish(species: "Sphyraena chrysotaenia", commonName: "Yellowstripe Barracuda", bengaliName: "হলদে ডোরা ধারকুটা", IUCN: "NE"),
  Fish(species: "Sphyraena forsteri", commonName: "Bigeye barracuda", bengaliName: "ধারকুটা", IUCN: "NE"),
  Fish(species: "Sphyraena jello", commonName: "Pickhandle barracuda", bengaliName: "ধারকুটা", IUCN: "NE"),
  Fish(species: "Sphyraena obtusata", commonName: "Obtuse barracuda", bengaliName: "ধারকুটা", IUCN: "NE"),
  Fish(species: "Sphyraena putnamae", commonName: "Sawtooth barracuda", bengaliName: "করাত দাতি ধারকুটা", IUCN: "LC"),
  Fish(species: "Sphyraena qenie", commonName: "Blackfin barracuda", bengaliName: "ধারকুটা", IUCN: "NE"),
  Fish(species: "Xiphias gladius", commonName: "Swordfish", bengaliName: "তলোয়ার মাছ", IUCN: "LC"),
  Fish(species: "Istiompax indica", commonName: "Black marlin", bengaliName: "কালো তলোয়ার", IUCN: "DD"),
  Fish(species: "Istiophorus platypterus", commonName: "Indo-Pacific sailfish", bengaliName: "পাল মাছ", IUCN: "LC"),
  Fish(species: "Callionymus carebares", commonName: "Indian deepwater dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "NE"),
  Fish(species: "Callionymus erythraeus", commonName: "Smallhead dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "NE"),
  Fish(species: "Callionymus margaretae", commonName: "Margaret’s dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "NE"),
  Fish(species: "Callionymus profundus", commonName: "Dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "NE"),
  Fish(species: "Callionymus sagitta", commonName: "Arrow dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "LC"),
  Fish(species: "Diplogrammus goramensis", commonName: "Goram dragonet", bengaliName: "ড্রাগনেট মাছ", IUCN: "NE"),
  Fish(species: "Neoepinnula orientalis", commonName: "Sack fish", bengaliName: "থলে মাছ", IUCN: "NE"),
  Fish(species: "Eupleurogrammus muticus", commonName: "Smallhead ", bengaliName: "ছুরি মাছ", IUCN: "NE"),
  Fish(species: "Lepturacanthus savala", commonName: "Savalai hairtail", bengaliName: "ছুরি মাছ", IUCN: "NE"),
  Fish(species: "Trichiurus gangeticus", commonName: "Ganges hairtail", bengaliName: "ছুরি মাছ", IUCN: "NE"),
  Fish(species: "Trichiurus lepturus", commonName: "Largehead ", bengaliName: "ছুরি মাছ", IUCN: "LC"),
  Fish(species: "Auxis rochei", commonName: "Bullet tuna", bengaliName: "টুনা মাছ", IUCN: "LC"),
  Fish(species: "Auxis thazard", commonName: "Frigate tuna", bengaliName: "টুনা মাছ", IUCN: "NE"),
  Fish(species: "Euthynnus affinis", commonName: "Kawakawa", bengaliName: "কাউয়া", IUCN: "LC"),
  Fish(species: "Katsuwonus pelamis", commonName: "Skipjack tuna", bengaliName: "টুনা মাছ", IUCN: "LC"),
  Fish(species: "Rastrelliger brachysoma", commonName: "Indian mackerel", bengaliName: "কাউয়া", IUCN: "DD"),
  Fish(species: "Rastrelliger faughni", commonName: "Island mackerel", bengaliName: "কাউয়া", IUCN: "DD"),
  Fish(species: "Rastrelliger kanagurta", commonName: "Indian mackerel", bengaliName: "কাউয়া", IUCN: "DD"),
  Fish(species: "Sarda orientalis", commonName: "Striped bonito", bengaliName: "টুনা মাছ", IUCN: "LC"),
  Fish(species: "Scomber australasicus", commonName: "Blue mackerel", bengaliName: "মাইট্টা", IUCN: "LC"),
  Fish(species: "Scomberomorus commerson", commonName: "Narrow-barred Spanish mackerel", bengaliName: "চম্পা", IUCN: "NT"),
  Fish(species: "Scomberomorus guttatus", commonName: "Indo-Pacific king mackerel", bengaliName: "মাইট্টা", IUCN: "DD"),
  Fish(species: "Scomberomorus koreanus", commonName: "Korean seerfish", bengaliName: "মাইট্টা", IUCN: "LC"),
  Fish(species: "Scomberomorus lineolatus", commonName: "Seer fish", bengaliName: "মাইট্টা", IUCN: "LC"),
  Fish(species: "Thunnus albacares", commonName: "Yellowfin tuna", bengaliName: "টুনা মাছ", IUCN: "NT"),
  Fish(species: "Thunnus obesus", commonName: "Bigeye tuna", bengaliName: "টুনা মাছ", IUCN: "VU"),
  Fish(species: "Thunnus tonggol", commonName: "Longtail tuna", bengaliName: "টুনা মাছ", IUCN: "DD"),
  Fish(species: "Cubiceps whiteleggii", commonName: "Shadow driftfish", bengaliName: "", IUCN: "NE"),
  Fish(species: "Ariomma indicum", commonName: "Indian driftfish", bengaliName: "মাখন চান্দা", IUCN: "NE"),
  Fish(species: "Pampus argenteus", commonName: "Silver pomfret", bengaliName: "ফালি চান্দা", IUCN: "NE"),
  Fish(species: "Pampus chinensis", commonName: "Chinese silver pomfret", bengaliName: "রূপচাঁদা", IUCN: "NE"),
  Fish(species: "Champsodon capensis", commonName: "Gaper", bengaliName: "কুমিরদাতি মাছ", IUCN: "LC"),
  Fish(species: "Parapercis alboguttata", commonName: "Whitespot sandsmelt", bengaliName: "বাইল্লা মাছ", IUCN: "LC"),
  Fish(species: "Parapercis diplospilus", commonName: "Latticed sandperch", bengaliName: "বাইল্লা মাছ", IUCN: "NE"),
  Fish(species: "Parapercis diplospilus", commonName: "Doublespot grubfish", bengaliName: "বাইল্লা মাছ", IUCN: "NE"),
  Fish(species: "Trichonotus setiger", commonName: "Spotted sanddiver", bengaliName: "", IUCN: "LC"),
  Fish(species: "Bembrops caudimacula", commonName: "Green humphead ", bengaliName: "চ্যাপ্টা মাছ", IUCN: "NE"),
  Fish(species: "Astroscopus guttatus", commonName: "Stargazer", bengaliName: "সাগর মাছ", IUCN: "LC"),
  Fish(species: "Ichthyscopus lebeck", commonName: "Longnosed stargazer", bengaliName: "সাগর মাছ", IUCN: "NE"),
  Fish(species: "Uranoscopus cognatus", commonName: "Two Spined ", bengaliName: "ত্যাড়া গজার", IUCN: "NE"),
  Fish(species: "Uranoscopus dollfusi", commonName: "Dollfus' stargazer", bengaliName: "সাগর বাইল্লা", IUCN: "LC"),
  Fish(species: "Uranoscopus fuscomaculatus", commonName: "Stargazer", bengaliName: "সাগর বাইল্লা", IUCN: "NE"),
  Fish(species: "Uranoscopus guttatus", commonName: "Dollfus' stargazer", bengaliName: "ত্যাড়া গজার", IUCN: "NE"),
  Fish(species: "Uranoscopus ", commonName: "Stargazer", bengaliName: "ত্যাড়া গজার", IUCN: "NE"),
  Fish(species: "Bodianus neilli", commonName: "Bay of Bengal hogfish", bengaliName: "", IUCN: "LC"),
  Fish(species: "Cheilinus chlorourus", commonName: "Floral wrasse", bengaliName: "কালা সুন্দরী", IUCN: "LC"),
  Fish(species: "Choerodon robustus", commonName: "Robust tuskfish", bengaliName: "", IUCN: "NE"),
  Fish(species: "Coris aygula", commonName: "Clown coris", bengaliName: "কালা ক্লাউন", IUCN: "LC"),
  Fish(species: "Coris gaimard", commonName: "African coris", bengaliName: "", IUCN: "LC"),
  Fish(species: "Halichoeres hortulanus", commonName: "Checkerboard wrasse", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Halichoeres marginatus", commonName: "Dusky wrasse", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Hemigymnus fasciatus", commonName: "Barred thicklip", bengaliName: "", IUCN: "LC"),
  Fish(species: "Labroides dimidiatus", commonName: "Bluestreak cleaner wrasse", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Thalassoma lunare", commonName: "Moon wrasse", bengaliName: "নিহলা", IUCN: "NE"),
  Fish(species: "Bolbometopon muricatum", commonName: " Green humphead ", bengaliName: "সবুজ কুজমাথা টিয়া মাছ", IUCN: "VU"),
  Fish(species: "Chlorurus japanensis", commonName: " Palecheek parrotfish", bengaliName: "", IUCN: "LC"),
  Fish(species: "Chlorurus rhakoura", commonName: "Raggedfin parrotfish", bengaliName: "কালা টিয়া", IUCN: "LC"),
  Fish(species: "Scarus ghobban", commonName: "Blue-barred parrotfish", bengaliName: "নীল টিয়া মাছ", IUCN: "LC"),
  Fish(species: "Scarus psittacus", commonName: "Common ", bengaliName: "টিয়া মাছ", IUCN: "LC"),
  Fish(species: "Scarus rivulatus", commonName: "Rivulated parrotfish", bengaliName: "টিয়া মাছ", IUCN: "LC"),
  Fish(species: "Scarus zufar", commonName: "Dhofar parrotfish", bengaliName: "টিয়া মাছ", IUCN: "LC"),
  Fish(species: "Lates calcarifer", commonName: "Asian seabass", bengaliName: "কোরাল", IUCN: "LC"),
  Fish(species: "Gerres argyreus", commonName: "Common silverbiddy", bengaliName: "", IUCN: "NE"),
  Fish(species: "Gerres erythrourus", commonName: "Deep-bodied mojarra", bengaliName: "", IUCN: "LC"),
  Fish(species: " Gerres filamentosus", commonName: "Whipfin silverbiddy", bengaliName: "দম মাছ", IUCN: "LC"),
  Fish(species: "Gerres infasciatus", commonName: "Nonbanded whipfin mojarra", bengaliName: "দম মাছ", IUCN: "DD"),
  Fish(species: "Gerres oblongus", commonName: "Slender silverbiddy", bengaliName: "", IUCN: "LC"),
  Fish(species: "Pentaprion longimanus", commonName: "Longfin mojarra", bengaliName: "জাগিরি", IUCN: "LC"),
  Fish(species: "Acropoma japonicum", commonName: "Glowbelly", bengaliName: "সামুদ্রিক পুটি মাছ", IUCN: "NE"),
  Fish(species: "Synagrops japonicus", commonName: "Blackmouth ", bengaliName: "", IUCN: "LC"),
  Fish(species: "Mulloidichthys vanicolensis", commonName: "Yellowfin goatfish", bengaliName: "ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Parupeneus forsskali", commonName: "Red sea goatfish", bengaliName: "ছাগল মাছ", IUCN: "NE"),
  Fish(species: "Parupeneus heptacanthus", commonName: "Goatfish", bengaliName: "ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Upeneus japonicus", commonName: "Japanese goatfish", bengaliName: "ছাগল মাছ", IUCN: "NE"),
  Fish(species: "Upeneus moluccensis", commonName: "Goldband goatfish", bengaliName: "সোনালিদাগী ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Upeneus sulphureus", commonName: "Sulphur goatfish", bengaliName: "সোনালি বাটা", IUCN: "LC"),
  Fish(species: "Upeneus sundaicus", commonName: "Ochrebanded goatfish", bengaliName: "সোনালি বাটা", IUCN: "LC"),
  Fish(species: "Upeneus supravittatus", commonName: "Long-fin goatfish", bengaliName: "ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Upeneus taeniopterus", commonName: "Finstripe goatfish", bengaliName: "ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Upeneus tragula", commonName: "Freckled goatfish", bengaliName: "সোনালি বাটা", IUCN: "LC"),
  Fish(species: "Upeneus vittatus", commonName: "Yellowstriped goatfish", bengaliName: "হলদেদাগি ছাগল মাছ", IUCN: "LC"),
  Fish(species: "Pempheris molucca", commonName: "Moluccansweeper", bengaliName: "লাল ফাইস্যা", IUCN: "NE"),
  Fish(species: "Neobathyclupea malayana", commonName: "Deepsea herring", bengaliName: "", IUCN: "NE"),
  Fish(species: "Kyphosus cinerascens", commonName: "Blue sea chub", bengaliName: "কালাফুনি/বিদা মাছ", IUCN: "LC"),
  Fish(species: "Kyphosus vaigiensis", commonName: "Brassy chub", bengaliName: "বিদা মাছ", IUCN: "LC"),
  Fish(species: "Pelates quadrilineatus", commonName: "Fourlined terapon", bengaliName: "বারগুনি", IUCN: "NE"),
  Fish(species: "Terapon jarbua", commonName: "Jarbua terapon", bengaliName: "বারগুনি", IUCN: "LC"),
  Fish(species: "Terapon theraps", commonName: "Largescaled terapon", bengaliName: "বারগুনি", IUCN: "LC"),
  Fish(species: "Cephalopholis boenak", commonName: "Chocolate hind", bengaliName: "চিত্রা বোল", IUCN: "LC"),
  Fish(species: "Cephalopholis formosa", commonName: "Bluelined hind", bengaliName: "নীলদাগী বোল", IUCN: "LC"),
  Fish(species: "Cephalopholis miniata", commonName: "Vermillion Grouper", bengaliName: "বোল মাছ", IUCN: "LC"),
  Fish(species: "Cephalopholis sonnerati", commonName: "Tomato hind", bengaliName: "চাটকি মাছ", IUCN: "LC"),
  Fish(species: "Chelidoperca margaritifera", commonName: "Pearly perchlet", bengaliName: "", IUCN: "NE"),
  Fish(species: "Cromileptes altivelis", commonName: "Humpback grouper", bengaliName: "কালোফোটা সাদা বোল", IUCN: "DD"),
  Fish(species: "Epinephelus bleekeri", commonName: "Duskytail grouper", bengaliName: "বোল মাছ", IUCN: "NT"),
  Fish(species: "Epinephelus chlorostigma", commonName: "Orangespotted Grouper", bengaliName: "বাদামি বোল", IUCN: "LC"),
  Fish(species: "Epinephelus coioides", commonName: "Orangespotted Grouper", bengaliName: "ফুটকি বোল", IUCN: "LC"),
  Fish(species: "Epinephelus erythrurus", commonName: "Cloudy Grouper", bengaliName: "চিত্রা বোল", IUCN: "LC"),
  Fish(species: "Epinephelus fasciatus", commonName: "Blacktip Grouper", bengaliName: "লাল বোল", IUCN: "LC"),
  Fish(species: "Epinephelus hexagonatus", commonName: "Starspotted grouper", bengaliName: "চিত্রা বোল", IUCN: "LC"),
  Fish(species: "Epinephelus lanceolatus", commonName: "Giant grouper", bengaliName: "বোল করা", IUCN: "DD"),
  Fish(species: "Epinephelus latifasciatus", commonName: "Striped grouper", bengaliName: "দাগি বোল", IUCN: "LC"),
  Fish(species: "Epinephelus malabaricus", commonName: "Malabar grouper", bengaliName: "বোল কোরাল", IUCN: "LC"),
  Fish(species: "Epinephelus merra", commonName: "Honeycomb grouper", bengaliName: "গুটি বোল", IUCN: "LC"),
  Fish(species: "Epinephelus morrhua", commonName: "Comet grouper", bengaliName: "বোল কোরাল", IUCN: "LC"),
  Fish(species: "Epinephelus polyphekadion", commonName: "Camouflage grouper", bengaliName: "কালো বোল", IUCN: "VU"),
  Fish(species: "Epinephelus quoyanus", commonName: "Longfin grouper", bengaliName: "চিত্রা বোল", IUCN: "LC"),
  Fish(species: "Epinephelus ", commonName: "Oblique-banded ", bengaliName: "বোল মাছ", IUCN: "LC"),
  Fish(species: "Epinephelus tauvina", commonName: "Grouper", bengaliName: "বোল", IUCN: "DD"),
  Fish(species: "Grammistes sexlineatus", commonName: "Goldenstriped soapfis", bengaliName: "", IUCN: "LC"),
  Fish(species: "Plectropomus leopardus", commonName: "Leopard coralgrouper", bengaliName: "চিত্রা বোল", IUCN: "LC"),
  Fish(species: "Plectropomus pessuliferus", commonName: "Roving coralgrouper", bengaliName: "লাল কোরাল বোল", IUCN: "LC"),
  Fish(species: "Lactarius lactarius", commonName: "False trevally", bengaliName: "সকেদি", IUCN: "NE"),
  Fish(species: "Monodactylus argenteus", commonName: "Silver moony", bengaliName: "আকালি চান্দা", IUCN: "LC"),
  Fish(species: "Aurigequula fasciata", commonName: "Striped ponyfish", bengaliName: "দাগি চান্দা", IUCN: "LC"),
  Fish(species: "Equulites elongatus", commonName: "Elongate ponyfish", bengaliName: "টেক চান্দা", IUCN: "NE"),
  Fish(species: "Equulites lineolatus", commonName: "Ornate ponyfish", bengaliName: "টেক চান্দা", IUCN: "NE"),
  Fish(species: "Eubleekeria splendens", commonName: "Splendid ponyfish", bengaliName: "কাটালি চান্দা", IUCN: "LC"),
  Fish(species: "Gazza minuta", commonName: "Toothpony", bengaliName: "দেঁতো চান্দা", IUCN: "LC"),
  Fish(species: "Leiognathus brevirostris", commonName: "Shortnose ponyfish", bengaliName: "টেক চান্দা", IUCN: "NE"),
  Fish(species: "Leiognathus equula", commonName: "Common ", bengaliName: "টেক চান্দা", IUCN: "LC"),
  Fish(species: "Nuchequula gerreoides", commonName: "Decorated ponyfish", bengaliName: "চান্দা", IUCN: "NE"),
  Fish(species: "Photopectoralis bindus", commonName: "Orangefin ponyfish", bengaliName: "কমলা চান্দা", IUCN: "NE"),
  Fish(species: "Secutor insidiator (", commonName: "Pugnose ponyfish", bengaliName: "ঠুটুনি চান্দা", IUCN: "NE"),
  Fish(species: "Secutor ruconius", commonName: "Deep pugnose ponyfish", bengaliName: "ঠুটুনি চান্দা", IUCN: "NE"),
  Fish(species: "Chaetodon collare Bloch", commonName: "Redtail butterflyfish", bengaliName: "লাল লেজা প্রজাপতি", IUCN: "LC"),
  Fish(species: "Chaetodon decussatus Cuvier", commonName: "Indian vagabond butterflyfish", bengaliName: "প্রজাপতি", IUCN: "LC"),
  Fish(species: "Chaetodon ", commonName: "Blackback butterflyfish", bengaliName: "প্রজাপতি", IUCN: "LC"),
  Fish(species: "Chaetodon octofasciatus Bloch", commonName: "Indian vagabond butterflyfish", bengaliName: "প্রজাপতি", IUCN: "LC"),
  Fish(species: "Chaetodon vagabundus Linnaeus", commonName: "Vagabond ", bengaliName: "হলুদ প্রজাপতি মাছ", IUCN: "LC"),
  Fish(species: "Heniochus acuminatus", commonName: "Pennat coralfish", bengaliName: "ডোরাকাটা প্রজাপতি মাছ", IUCN: "LC"),
  Fish(species: "Heniochus singularius", commonName: "Singular bannerfish", bengaliName: "প্রজাপতি", IUCN: "LC"),
  Fish(species: "Parachaetodon ocellatus", commonName: "Sixspine butterflyfish", bengaliName: "ডোরাকাটা প্রজাপতি মাছ", IUCN: "LC"),
  Fish(species: "Roa Joyakari", commonName: "Indian golden", bengaliName: "প্রজাপতি", IUCN: "LC"),
  Fish(species: "Pomacanthus annularis", commonName: "Bluering angelfish", bengaliName: "দুধকমল", IUCN: "LC"),
  Fish(species: "Pomacanthus imperator", commonName: "Empereor angelfish", bengaliName: "রাজা দুধকমল", IUCN: "LC"),
  Fish(species: "Pomacanthus ", commonName: "Semicircle ", bengaliName: "দুধকমল", IUCN: "LC"),
  Fish(species: "Pomacanthus sexstriatus", commonName: "Sixbar angelfish", bengaliName: "ছয়দাগী দুধকমল", IUCN: "LC"),
  Fish(species: "Abudefduf bengalensis", commonName: "Bengal sergeant", bengaliName: "পাথারি", IUCN: "LC"),
  Fish(species: "Abudefduf septemfasciatus", commonName: "Banded sergeant", bengaliName: "পাথারি", IUCN: "LC"),
  Fish(species: "Abudefduf sexfasciatus", commonName: "Scissortail sergeant", bengaliName: "পাথারি", IUCN: "NE"),
  Fish(species: "Abudefduf sordidus", commonName: "Blackspot sergeant", bengaliName: "পাথারি", IUCN: "LC"),
  Fish(species: "Abudefduf vaigiensis", commonName: "Indo-specific sergeant", bengaliName: "পাথারি", IUCN: "LC"),
  Fish(species: "Amphiprion ephippium", commonName: "Saddle anemonefish", bengaliName: "মুধাহ", IUCN: "LC"),
  Fish(species: "Amphiprion percula", commonName: "Orange clownfish", bengaliName: "পরি মাছ", IUCN: "NE"),
  Fish(species: "Cheiloprion labiatus", commonName: "Big-lip damsel", bengaliName: "মুধাহ", IUCN: "NE"),
  Fish(species: "Chromis cinerascens", commonName: "Green puller", bengaliName: "পেত্তলি", IUCN: "LC"),
  Fish(species: "Chromis", commonName: "Ternate chromis", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Chromis", commonName: "Blue green damselfish", bengaliName: "নীলিমা", IUCN: "NE"),
  Fish(species: "Chrysiptera brownriggii", commonName: "Surge damselfish", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Chrysiptera unimaculata", commonName: "Onespot demoiselle", bengaliName: "পেত্তলি", IUCN: "LC"),
  Fish(species: "Dascyllus marginatus", commonName: "Marginate dascyllus", bengaliName: "পান্দুয়া", IUCN: "NE"),
  Fish(species: "Dischistodus perspicillatus", commonName: "White damsel", bengaliName: "আফু", IUCN: "NE"),
  Fish(species: "Dischistodus prosopotaenia", commonName: "Honey-head damsel", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Neopomacentrus azysron", commonName: "Yellowtail demoiselle", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Neopomacentrus cyanomous", commonName: "Regal demoiselle", bengaliName: "পেত্তলি", IUCN: "VU"),
  Fish(species: "Neopomacentrus taeniurus", commonName: "Freshwater demoiselle", bengaliName: "পেত্তলি", IUCN: "DD"),
  Fish(species: "pomacentrus adelus", commonName: "Obscure damsel", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "pomacentrus bangladeshius", commonName: "Bengal demoiselle", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "pomacentrus caeruleus", commonName: "Caerulean damsel", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "pomacentrus", commonName: "Neon damselfish", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "pomacentrus proteus", commonName: "Colombo damsel", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Pomacentrus similis", commonName: "Similar damsel", bengaliName: "পেত্তলি", IUCN: "NE"),
  Fish(species: "Pomacentrus tripunctatus", commonName: "Threespot damsel", bengaliName: "পেত্তলি", IUCN: " NE"),
  Fish(species: "Pomacentrus vaiuli", commonName: "Ocellate damselfish", bengaliName: "লাল ক্লাউন মাছ", IUCN: " NE"),
  Fish(species: "Premnas biaculeatus", commonName: "Spinecheek anemonefish", bengaliName: "পেত্তলি", IUCN: " NE"),
  Fish(species: "Pristotis obtusirostris", commonName: "Gulf damselfish", bengaliName: "পেত্তলি", IUCN: " NE"),
  Fish(species: "Stegastes fasciolatus", commonName: "Pacific gregory", bengaliName: "পেত্তলি", IUCN: " NE"),
  Fish(species: "Stegastes obreptus", commonName: "Western gregory", bengaliName: "পেত্তলি", IUCN: " NE"),
  Fish(species: "Heteropriacanthus cruentatus", commonName: "Glasseye", bengaliName: "", IUCN: "LC"),
  Fish(species: "Priacanthus hamrur", commonName: "Moontail bullseye", bengaliName: "রাঙ্গা পরী", IUCN: "LC"),
  Fish(species: "Priacanthus sagittarius", commonName: "Arrow bulleye", bengaliName: "রাঙ্গা পরী", IUCN: "LC"),
  Fish(species: "Priacanthus tayenus", commonName: "Purple-spotted bigeye", bengaliName: "রাঙ্গা পরী", IUCN: "LC"),
  Fish(species: "Diagramma pictum", commonName: "Painted sweetlips", bengaliName: "রঙিন ঠোঁটা", IUCN: " NE"),
  Fish(species: "Plectorhinchus cinctus", commonName: "Crescent sweetlips", bengaliName: "দাতিনা", IUCN: " NE"),
  Fish(species: "Plectorhinchus vittatus", commonName: "Indian Ocean oriental sweetlips", bengaliName: "দাতিনা", IUCN: "LC"),
  Fish(species: "Pomadasys argenteus", commonName: "Silver grunt", bengaliName: "রূপালি দাতিনা", IUCN: "LC"),
  Fish(species: "Pomadasys argyreus", commonName: "Bluecheek silver grunt", bengaliName: "নীলগালি রূপালি দাতিনা", IUCN: "LC"),
  Fish(species: "Pomadasys furcatus", commonName: "Banded grunter", bengaliName: "ডোরাকাটা দাতিনা", IUCN: "LC"),
  Fish(species: "Pomadasys kaakan", commonName: "Javelin grunter", bengaliName: "নাক কোরাল", IUCN: "NE"),
  Fish(species: "Pomadasys ", commonName: "Saddle grunt", bengaliName: "গুটি দাতিনা", IUCN: "LC"),
  Fish(species: "Pomadasys multimaculatus", commonName: "Cock grunter", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus argentimaculatus", commonName: " Mangrove red snapper", bengaliName: "রাঙ্গা চৌক্ষা", IUCN: "LC"),
  Fish(species: "Lutjanus bohar", commonName: " Two-spot red snapper", bengaliName: "লাল রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus ehrenbergii", commonName: "Blackspot snapper", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus erythropterus", commonName: " Crimson snapper", bengaliName: "চৌক্ষা/ছই", IUCN: "LC"),
  Fish(species: "Lutjanus fulviflamma", commonName: "Dory snapper", bengaliName: "দড়ি ছই/রাশরি", IUCN: " LC"),
  Fish(species: "Lutjanus fulvus", commonName: " Blacktail snapper", bengaliName: "কালো লেঞ্জা চউক্ষা", IUCN: "LC"),
  Fish(species: "Lutjanus gibbus", commonName: "Humpback red snapper", bengaliName: "কুজো রাঙ্গা চৌক্ষা", IUCN: "LC"),
  Fish(species: "Lutjanus indicus", commonName: " Indian Snapper", bengaliName: "রাঙ্গা চৌক্ষা", IUCN: "LC"),
  Fish(species: "Lutjanus johnii", commonName: " John's snapper", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus lemniscatus", commonName: "Yellowstreaked snapper", bengaliName: "লাল কোরাল", IUCN: "LC"),
  Fish(species: "Lutjanus lunulatus", commonName: " Lunartail snapper", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus Lutjanus", commonName: "Big-eye snapper", bengaliName: "খোলাদ্দিয়া মাছ", IUCN: "LC"),
  Fish(species: "Lutjanus malabaricus", commonName: "Malabar blood snapper", bengaliName: "মোটা ঠোঁট কোরাল", IUCN: "LC"),
  Fish(species: "Luijanus rivulatus", commonName: "Blubberlip snapper", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus sanguineus", commonName: "Humphead snapper", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus sabae", commonName: "Emperor ", bengaliName: "রাঙ্গা ছই", IUCN: "LC"),
  Fish(species: "Lutjanus vitta", commonName: "Brownstripe", bengaliName: "বাদামদাগি ছই", IUCN: "LC"),
  Fish(species: "Lutjanus xanthopinnis", commonName: "Yellowfin", bengaliName: "পিনজালো", IUCN: "DD"),
  Fish(species: "Pinjalo pinjalo", commonName: "Pinjalo snapper", bengaliName: "পিনজালো ছই", IUCN: "LC"),
  Fish(species: "Pristipomoides filamentosus", commonName: "Crimson jobfish", bengaliName: "লালমাছ", IUCN: "LC"),
  Fish(species: "Pristipomoides multidens", commonName: "Goldbanded", bengaliName: "লালমাছ", IUCN: "LC"),
  Fish(species: "Caesio calerulaurea", commonName: "Blue gold", bengaliName: "নীল সোনালি ফুসিলার", IUCN: "LC"),
  Fish(species: "Caesio cunning", commonName: "Redbelly", bengaliName: "লাল পেট ফুসিলার", IUCN: "LC"),
  Fish(species: "Caesio xanthonota", commonName: "Yellowback ", bengaliName: "হলদে পিঠে ফুসিলার", IUCN: "LC"),
  Fish(species: "Cirrhitichthys bleekeri", commonName: "Hawkfish", bengaliName: "", IUCN: "LC"),
  Fish(species: "Acanthocepola indica", commonName: "Deep sea snake fish", bengaliName: "", IUCN: "LC"),
  Fish(species: "Scatophagus argus", commonName: "Spotted seut", bengaliName: "বিশতারা", IUCN: "LC"),
  Fish(species: "Siganus canaliculatus", commonName: "Whitespottedspinefoot", bengaliName: "সাদাফোটা বিশকাঠালি", IUCN: "LC"),
  Fish(species: "Siganusjavus", commonName: "Streakedspinefo ot", bengaliName: "বিশকাঠালি", IUCN: "LC"),
  Fish(species: "Siganus stellatus", commonName: "Brown-", bengaliName: "খয়রিফোটা বিশকাঠালি", IUCN: "LC"),
  Fish(species: "Siganus vermiculatus", commonName: "Vermiculatedspi nefoot", bengaliName: "পান মাছ", IUCN: "LC"),
  Fish(species: "Drepane longimana", commonName: "BandedDrepane", bengaliName: "পান মাছ", IUCN: "NE"),
  Fish(species: "Drepane punctata", commonName: "Spottedsicklefis h", bengaliName: "পান মাছ", IUCN: "LC"),
  Fish(species: "Ephippus orbis", commonName: "Orbfish", bengaliName: "বাদুড় মাছ", IUCN: "NE"),
  Fish(species: "Platax orbicularis", commonName: "Orbicularbatfish", bengaliName: "টায়রা মাছ", IUCN: "LC"),
  Fish(species: "Platax teira", commonName: "Longfinbatfish", bengaliName: "কুলা মাছ", IUCN: "LC"),
  Fish(species: "Tripter odonorbis", commonName: "Africanspadefish", bengaliName: "পোয়া", IUCN: "NE"),
  Fish(species: "Argyrosomusamoye", commonName: "Amoycroaker", bengaliName: "পোয়া", IUCN: "EN"),
  Fish(species: "Argyrosomusjaponi cus", commonName: "Japanesemeagre", bengaliName: "পোয়া", IUCN: "EN"),
  Fish(species: "Argyrosomusthorpei", commonName: "Japanesemeagre", bengaliName: "পোয়া", IUCN: "EN"),
  Fish(species: "Atrobuccanibe", commonName: "Blackmouthcroa ker", bengaliName: "কালামুখি পোয়া", IUCN: "LC"),
  Fish(species: "Chrysochiraureus", commonName: "Croaker", bengaliName: "ধারি পোয়া", IUCN: "LC"),
  Fish(species: "Dendrophysarusseli i", commonName: "Goateecroaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Johnius amblycephalus", commonName: "Bearded croaker", bengaliName: "রূপালি পোয়া", IUCN: "LC"),
  Fish(species: "Johnius belangerii", commonName: "Belanger's croaker", bengaliName: "মেটে রঙের পোয়া", IUCN: "NE"),
  Fish(species: "Johnius borneensis", commonName: "Sharpnose hammer croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Johnius carutta", commonName: "Karut croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Johnius coitor", commonName: "Coitor/ Crocker", bengaliName: "কালা পোয়া", IUCN: "LC"),
  Fish(species: "Johnius dussumieri", commonName: "Sin croaker", bengaliName: "বাঁশ পোয়া", IUCN: "LC"),
  Fish(species: "Johnius elongatus", commonName: "Spindle croaker", bengaliName: "পোয়া", IUCN: "DD"),
  Fish(species: "Johnius macropterus", commonName: "Largefin croaker", bengaliName: "কালা পোয়া", IUCN: "LC"),
  Fish(species: "Johnius plagiostoma", commonName: "Large-eye Croaker", bengaliName: "পোয়া মাছ", IUCN: "LC"),
  Fish(species: "Kathala axillaris", commonName: "Kathala croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Macrospinosa cuja", commonName: "Cuja Croaker", bengaliName: "পোয়া", IUCN: "DD"),
  Fish(species: "Nibea maculata", commonName: "Blotched croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Otolithes cuvieri", commonName: "Lesser tiger toothed croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Otolithes ruber", commonName: "Tigertooth croaker", bengaliName: "লাম্বু", IUCN: "LC"),
  Fish(species: "Otolithoides biauritus", commonName: "Bronze croaker", bengaliName: "লম্বু পোয়া", IUCN: "DD"),
  Fish(species: "Otolithoides pama", commonName: "Pama croaker", bengaliName: "লেইজ্জা পোয়া", IUCN: "DD"),
  Fish(species: "Panna heterolepis", commonName: "Hooghly croaker", bengaliName: "ছোট্টা লাম্বু", IUCN: "LC"),
  Fish(species: "Panna microdon", commonName: "Panna croaker", bengaliName: "লাল পোয়া", IUCN: "LC"),
  Fish(species: "Paranibea semiluctuosa", commonName: "Half-mourning croaker", bengaliName: "সাদা পোয়া", IUCN: "LC"),
  Fish(species: "Pennahia anea", commonName: "Bigeye croaker", bengaliName: "বড়োচোখা পোয়া", IUCN: "LC"),
  Fish(species: "Pennahia argentata", commonName: "Silver croake", bengaliName: "রূপালি পোয়া", IUCN: "LC"),
  Fish(species: "Pennahia ovata", commonName: "Big Head ", bengaliName: "কালা পোয়া", IUCN: "DD"),
  Fish(species: "Protonibea diacanthus", commonName: "Blackspotted croaker", bengaliName: "কালো পোয়া", IUCN: "NT"),
  Fish(species: "Pseudotolithus elongatus", commonName: "Spindle Croaker", bengaliName: "পোয়া", IUCN: "LC"),
  Fish(species: "Pterotolithus lateoides", commonName: "Bigmouth croake", bengaliName: "", IUCN: "DD"),
  Fish(species: "Pterotolithus maculatus", commonName: "Blotched tigertoothed croaker", bengaliName: "গুটি পোয়া", IUCN: "LC"),
  Fish(species: "Acanthurus lineatus", commonName: "Lined surgeonfish", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Acanthurus mata", commonName: "Elongate surgeonfish", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Acanthurus xanthopterus", commonName: "Yellowfin surgeonfish", bengaliName: "সুন্দরী মাছ", IUCN: "LC"),
  Fish(species: "Sillaginopsis panijus", commonName: "Flathead sillago", bengaliName: "তুলারডান্ডি", IUCN: "NE"),
  Fish(species: "Sillago maculata", commonName: "Trumpeter sillago", bengaliName: "সুন্দ্রা", IUCN: "NE"),
  Fish(species: "Sillago sihama", commonName: "Silver sillago", bengaliName: "সুন্দরি বাইল্লা", IUCN: "LC"),
  Fish(species: "Lobotes surinamensis", commonName: "Tripletail", bengaliName: "সমুদ্র কই", IUCN: "LC"),
  Fish(species: "Nemipterus bipunctatus", commonName: "Delagoa threadfin bream", bengaliName: "গোলাপি রূপবান", IUCN: "LC"),
  Fish(species: "Nemipterus furcosus", commonName: "Fork-tailed threadfin bream", bengaliName: "সাত দাগি রূপবান", IUCN: "LC"),
  Fish(species: "Nemipterus gracilis", commonName: "Graceful threadfin bream", bengaliName: "রূপবান", IUCN: "NE"),
  Fish(species: "Nemipterus japonicus", commonName: "Japanese threadfin bream", bengaliName: "রূপবান", IUCN: "LC"),
  Fish(species: "Nemipterus nematophorus", commonName: "Double whip threadfin", bengaliName: "পাখা কাটা সোনাবাম", IUCN: "LC"),
  Fish(species: "Nemipterus peronii", commonName: "Notched Fin threadfin bream", bengaliName: "সোনাবাম", IUCN: "LC"),
  Fish(species: "Nemipterus randalli", commonName: "Randall's threadfin bream", bengaliName: "লাল মাছ", IUCN: "LC"),
  Fish(species: "Parascolopsis aspinosa", commonName: "Smooth dwarf monocle bream", bengaliName: "সোনাবান মাছ", IUCN: "LC"),
  Fish(species: "Scolopsis bimaculata", commonName: "Thumbprint monocle bream", bengaliName: "কারুয়া কোরাল", IUCN: "LC"),
  Fish(species: "Scolopsis vosmeri", commonName: "White cheek ", bengaliName: "কারুয়া কোরাল", IUCN: "LC"),
  Fish(species: "Gymnocranius griseus", commonName: "Grey large eye bream", bengaliName: "বড়ো চোখা কোরাল", IUCN: "LC"),
  Fish(species: "Lethrinus erythyracanthus", commonName: "Orange-spotted emperor", bengaliName: "কারুয়া কোরাল", IUCN: "LC"),
  Fish(species: "Lethrinus lentjan", commonName: "Pink ear emperor", bengaliName: "কারুয়া কোরাল", IUCN: "LC"),
  Fish(species: "Lethrinus nebulosus", commonName: "Spangled emperor", bengaliName: "দাতিনা", IUCN: "LC"),
  Fish(species: "Lethrinus olivaceus", commonName: "Long face emperor", bengaliName: "দাতিনা", IUCN: "LC"),
  Fish(species: "Lethrinus ornatus", commonName: "Ornate emperor", bengaliName: "ওটা", IUCN: "LC"),
  Fish(species: "Acanthopagrus berda", commonName: "Goldsilk seabream", bengaliName: "কালো দাতিনা", IUCN: "LC"),
  Fish(species: "Acanthopagrus latus", commonName: "Yellow seabrem", bengaliName: "লাল দাতিনা", IUCN: "DD"),
  Fish(species: "Argyrops spinifer", commonName: "King soldier bream", bengaliName: "দাতিনা", IUCN: "LC"),
  Fish(species: "Sparidentex datnia", commonName: "Yellowfin seabream", bengaliName: "দাতিনা", IUCN: "DD"),
  Fish(species: " Antigonia rubescens", commonName: "Indo-Pacific boarfish", bengaliName: "", IUCN: "NE"),
  Fish(species: "Zanclus cornutus", commonName: "Moorish idol", bengaliName: "উড়ুক্কু মাছ", IUCN: "LC"),
  Fish(species: "Dactyloptena orientalis", commonName: "Oriental flying gurnard", bengaliName: "উড়ুক্কু মাছ", IUCN: "LC"),
  Fish(species: "Ebosia falcata", commonName: "Cocks comb fire fish", bengaliName: "রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Pterois miles", commonName: "Miles lion fish", bengaliName: "মিলি রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Pterois mombasae", commonName: "Frillfin turkeyfish", bengaliName: "রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Pterois russelii", commonName: "Plaintail turkeyfish", bengaliName: "রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Pterois volitans", commonName: "Red lionfish", bengaliName: "রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Scorpaenodes guamensis", commonName: "Guam ", bengaliName: "কাটাবুল", IUCN: "LC"),
  Fish(species: "Scorpaenodes investigatoris", commonName: "Scorpionfish", bengaliName: "কাটাবুল", IUCN: "LC"),
  Fish(species: "Scorpaenodes scaber", commonName: "Pygmy ", bengaliName: "বামুন কাটাবুল", IUCN: "DD"),
  Fish(species: "Lepidotrigla bispinosa", commonName: "Bullhorn gurnard", bengaliName: "সিঙ্গি রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Lepidotrigla spiloptera", commonName: "Spotwing gurnard", bengaliName: "দাগিপাখনা রঙ্গিলা", IUCN: "LC"),
  Fish(species: "Pterygotrigla arabica", commonName: "Gurnard fish", bengaliName: "কুমির মাছ", IUCN: "NE"),
  Fish(species: "Satyrichthys laticeps", commonName: "Flatheads", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Bembras japonica", commonName: "Deepwater flathead", bengaliName: "বাইলা/বেলে", IUCN: "NE"),
  Fish(species: "Cociella crocodilus", commonName: "Spotted flathead", bengaliName: "বাইলা/বেলে", IUCN: "LC"),
  Fish(species: "Cociella punctata", commonName: "Flathead", bengaliName: "মুর বাইলা", IUCN: "LC"),
  Fish(species: "Grammoplites scaber", commonName: "Rough flathead", bengaliName: "মুর বাইলা", IUCN: "NE"),
  Fish(species: "Grammoplites suppositus", commonName: "Spotfin flathead", bengaliName: "মুর বাইলা", IUCN: "LC"),
  Fish(species: "Kumococius rodericensis", commonName: "Spiny flathead", bengaliName: "মুর বাইলা", IUCN: "LC"),
  Fish(species: "Onigocia pedimacula", commonName: "Broadband flathead", bengaliName: "বড়ো মাথা বাইলা", IUCN: "LC"),
  Fish(species: "Platycephalus indicus", commonName: "Bartail flathead", bengaliName: "সাগর বাইলা", IUCN: "DD"),
  Fish(species: "Rogadius asper", commonName: "Olive-tailed flathead", bengaliName: "সাগর বাইলা", IUCN: "LC"),
  Fish(species: "Rogadius pristiger", commonName: "Flathead", bengaliName: "সাগর বাইলা", IUCN: "LC"),
  Fish(species: "Sorsogona tuberculata", commonName: "Tuberculated flathead", bengaliName: "সাগর বাইলা", IUCN: "LC"),
  Fish(species: "Sunagocia carbunculus", commonName: "Papillose flathead", bengaliName: "সাগর বাইলা", IUCN: "LC"),
  Fish(species: "Apistus carinatus", commonName: "Ocellated waspfish", bengaliName: "", IUCN: "N.T"),
  Fish(species: "Tetraroge niger", commonName: "Roguefish", bengaliName: "কাটা কোরাল", IUCN: "L.C"),
  Fish(species: "Minous monodactylus", commonName: "Grey stingfish", bengaliName: "কাটা কোরাল", IUCN: "L.C"),
  Fish(species: "Minous pictus", commonName: "Painted stinger", bengaliName: "রঙ্গিলা কাটা কোরাল", IUCN: "L.C"),
  Fish(species: "Lophiodes mutilus", commonName: "Smooth angler", bengaliName: "সমুদ্র কোরাল", IUCN: "L.C"),
  Fish(species: "Lophiodes naresi", commonName: "Goosefish", bengaliName: "সমুদ্র কোরাল", IUCN: "L.C"),
  Fish(species: "Antennarius hipidus", commonName: "Shaggy angler", bengaliName: "ব্যাঙ মাছ", IUCN: "N.T"),
  Fish(species: "Halieutaea indica", commonName: "Indian handfish", bengaliName: "লাল বাদুড় মাছ", IUCN: "L.C"),
  Fish(species: "Halieutaea stellata", commonName: "Minipizza batfish", bengaliName: "সমুদ্র মাছ", IUCN: "L.C"),
  Fish(species: "Halimochirurgus alcocki", commonName: "Alcock's Spikefish", bengaliName: "সুকুরা", IUCN: "N.T"),
  Fish(species: "Pseudotriacanthus strigilifer", commonName: "Long-spined tripodfish", bengaliName: "সুকুরা", IUCN: ""),
  Fish(species: "Triacanthus biaculeatus", commonName: "Short-nosed tripodfish", bengaliName: "পান বিড়ি সিগারেট/তেকাঠি", IUCN: "L.C"),
  Fish(species: "Triacanthus nieuhofii", commonName: "Silver tripodfish", bengaliName: "পান বিড়ি সিগারেট/তেকাঠি", IUCN: "N.T"),
  Fish(species: "Lactoria cornuta", commonName: "Longhorn cowfish", bengaliName: "বিগশ মাছ", IUCN: "N.T"),
  Fish(species: "Ostracion cubicus", commonName: "Yellow boxfish", bengaliName: "বিগশ মাছ", IUCN: "L.C"),
  Fish(species: "Rhynchostracion nasus", commonName: "Shortnose boxfish", bengaliName: "বিগশ মাছ", IUCN: "N.T"),
  Fish(species: "Tetrosomus gibbosus", commonName: "Humback ", bengaliName: "সাগর পটকা", IUCN: "LC"),
  Fish(species: "Abalistes stellatus", commonName: "Starry triggerfish", bengaliName: "সরল", IUCN: "LC"),
  Fish(species: "Pseudobalistes flavimarginatus", commonName: "Yellow margin", bengaliName: "সরল", IUCN: "NE"),
  Fish(species: "Sufflamen fraenatum", commonName: "Masked", bengaliName: "সরল", IUCN: "LC"),
  Fish(species: "Aluterus monoceros", commonName: "Unicorn leather", bengaliName: "পটকা", IUCN: "LC"),
  Fish(species: "Aluterus scriptus", commonName: "Scribbled leather", bengaliName: "পটকা", IUCN: "LC"),
  Fish(species: "Arothron immaculatus", commonName: "Immaculate", bengaliName: "পটকা", IUCN: "ND"),
  Fish(species: "Arothron leopardus", commonName: "Banded leopard blow fish", bengaliName: "রেখা পটকা", IUCN: "ND"),
  Fish(species: "Arothron reticularis", commonName: "Reticulated pufferfish", bengaliName: "বাদামি পটকা", IUCN: "LC"),
  Fish(species: "Arothron stellatus", commonName: "Stellate", bengaliName: "পটকা", IUCN: "LC"),
  Fish(species: "chelonodontops ", commonName: "Bengal ", bengaliName: "", IUCN: "NE"),
  Fish(species: "chelonodontops patoca", commonName: "Milksootted", bengaliName: "সাদা ফোঁটা পটকা মাছ", IUCN: "LC"),
  Fish(species: "Lagocephalus guentheri", commonName: "Diamond back", bengaliName: "পটকা", IUCN: "NE"),
  Fish(species: "Lagocephalus lagocephalus", commonName: "Oceanic", bengaliName: "সাগর পটকা", IUCN: "LC"),
  Fish(species: "Lagocephalus lunaris", commonName: "Lunartail Puffer", bengaliName: "পটকা", IUCN: "LC"),
  Fish(species: "Lagocephalus sceleratus", commonName: "Silver cheeked toadfish", bengaliName: "রূপালি পটকা", IUCN: "LC"),
  Fish(species: "Lagocephalus spadiceus", commonName: "Half-smooth golden puffer fish", bengaliName: "দোরা পটকা/ সোনালি আভা পটকা", IUCN: "L.C"),
  Fish(species: "Takifugu oblongus", commonName: "Lattice blaasop", bengaliName: "ডোরা পটকা", IUCN: "L.C"),
  Fish(species: "Cyclichthys orbicularis", commonName: "Birdbeak burrfish", bengaliName: "সজারু পটকা", IUCN: "N.E"),
  Fish(species: "Diodon hystrix", commonName: "Spot fin porcupinefish", bengaliName: "সজারু পটকা", IUCN: "L.C"),
  Fish(species: "penaeus monodon", commonName: "giant tiger shrimp", bengaliName: "বাগদা চিংড়ি", IUCN: ""),
  Fish(species: "Metapenaeus affinis", commonName: "Jinga shrimp", bengaliName: "লইল্যা চিংড়ি", IUCN: ""),
  Fish(species: "Penaeus indicus", commonName: "Indian white shrimp", bengaliName: "চাগা চিংড়ি", IUCN: ""),
  Fish(species: "Metapenaeus brevicornis", commonName: "Yellow shrimp", bengaliName: "লইল্যা চিংড়ি", IUCN: ""),
  Fish(species: "Penaeus semisulcatus", commonName: "Green tiger shrimp", bengaliName: "বাঘা তারা চিংড়ি", IUCN: ""),
  Fish(species: "Parapenaeopsis sculptillis", commonName: "Rainbow shrimp", bengaliName: "রুডা চিংড়ি", IUCN: ""),
  Fish(species: "Mdetapeneaus monoceros", commonName: "Speckled Shrimp", bengaliName: "হরিণা চিংড়ি", IUCN: ""),
  Fish(species: "Metapenaeus stylifera", commonName: "Kiddi shrimp", bengaliName: "রুডা চিংড়ি", IUCN: ""),
  Fish(species: "Scylla serrata", commonName: "mud crab", bengaliName: "শিলা কাকড়া", IUCN: ""),
  Fish(species: "Panulirus polyphagus", commonName: "Mud spiny lobster", bengaliName: "ছোয়া ইছা", IUCN: ""),
  Fish(species: "Portunus polagicus", commonName: "Blue swimmer crab", bengaliName: "ঝাঁঝি কাঁকড়া", IUCN: ""),
  Fish(species: "Portunus sanguinolentus", commonName: "Swimmer crab", bengaliName: "ঝাঁঝি কাঁকড়া", IUCN: ""),
  Fish(species: "Panulirus hurmarus", commonName: "Mud spiny lobster", bengaliName: "লবস্টার", IUCN: ""),
  Fish(species: "Thenus orientalis", commonName: "Flathead locus lobster", bengaliName: "বেলানেছা লবস্টার", IUCN: ""),
];